// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/jinzhu/gorm"
	"github.com/teten-nugraha/golang-crud/handler"
	"github.com/teten-nugraha/golang-crud/repository"
	"github.com/teten-nugraha/golang-crud/service"
)

// Injectors from wire.go:

func InitMonoAPI(db *gorm.DB) handler.MonoAPI {
	monoRepository := repository.ProviderMonoRepository(db)
	monoServiceContract := service.ProviderMonoService(monoRepository)
	monoAPI := handler.ProviderMonoAPI(monoServiceContract)
	return monoAPI
}
