// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injection

import (
	"github.com/jinzhu/gorm"
	"github.com/teten-nugraha/golang-crud/handler"
	"github.com/teten-nugraha/golang-crud/repository"
	"github.com/teten-nugraha/golang-crud/service"
)

// Injectors from wire.go:

func InitMonoAPI(db *gorm.DB) handler.MonoAPI {
	MonoRepository := repository.ProviderMonoRepository(db)
	MonoService := service.ProviderMonoService(MonoRepository)
	MonoAPI := handler.ProviderMonoAPI(MonoService)
	return MonoAPI
}